# SPDX-FileCopyrightText: Copyright (C) 2022, vDL Digital Ventures GmbH <info@vdl.digital>
# SPDX-FileCopyrightText: Copyright (C) 2021, Spruce Systems, Inc.
#
# SPDX-License-Identifier: MIT

plugin_name:
  discourse_siwt_enabled:
    default: false
    client: true
  discourse_siwt_statement:
    client: true
    default: "Sign-in to Discourse with your Tezos account"
